#!/bin/bash

set -euo pipefail
IFS=

# try to get the *newest* version available, unlike Debian's default
# which is the oldest (right?)

die () {
    {
        echo "Could not find any clang compiler under clang-<versionnumber>."
        echo "Please \`apt install clang-10\` or so."
    } >&2
    echo false
    exit 1
}

which clang-10 || which clang-9 || which clang-8 || which clang-7 || which clang-6 || die
